/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.height.app;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        Links links = objectMapper.readValue(new File("C:/dev/height-tree/app/src/main/resources/tree.json"), Links.class);
        System.out.println(links);
    }
}
