/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("tree.height.java-application-conventions")
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.1")
}

application {
    // Define the main class for the application.
    mainClass.set("tree.height.app.App")
}
